config/routes.rb
IaApp::Application.routes.draw do
  resources :users
  resources :characters
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup',  :to => 'users#new'
  
  match '/signin',  :to => 'sessions#new'
  match '/sign_in',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'


  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  
  match '/newchar', :to => 'characters#new'
  match '/race_info', :to => 'characters#race_info'
  
  root :to => 'pages#home' 
end

app/views/pages/about.html.erb
<h1>About Us</h1>

<p>
  This Database portal was written using Ruby on Rails with the assistance of the 
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  , a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>.
</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>
  Please feel free to contact aegora on the IA forums if you have any questions concerning this site.
</p>

app/views/pages/help.html.erb
<h1>Help</h1>
<p>
  Get help on Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/pages/home.html.erb
<h1>Welcome</h1>
<p>
  This is the Inritius Alliance Character Database page. 
 </p>
<p> 
  Through this portal you are able to access the official versions of your character to
  add or modify skills or manage the items on your character sheet.
</p>
 <% if signed_in? %>
     
 <!-- # changes to character_path later ... -->    
<%= link_to "Character List", characters_path, :class => "signup_button round" %>

<% else %>
      
<%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>

<% end %>
      
      