config/routes.rb
IaApp::Application.routes.draw do
  resources :users
  resources :characters
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup',  :to => 'users#new'
  
  match '/signin',  :to => 'sessions#new'
  match '/sign_in',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'


  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  
  match '/newchar', :to => 'characters#new'
  match '/race_info', :to => 'characters#race_info'
  
  root :to => 'pages#home' 
end

app/models/character.rb
#  This is the base character model.
#
# Character models possess only the skeletal information on a character,
# things that don't really change too much.



class Character < ActiveRecord::Base
	 attr_accessible :backstory, :character_name, :race, :gender, :alignment, :deity,
  	 :multiplier_agility, :multiplier_connection, :multiplier_intellect, :multiplier_might, 
	 :multiplier_magic, :primary_sphere


	 belongs_to :user
	 has_many :skills, :dependent => :destroy
	 has_many :experiences, :dependent => :destroy
	 has_many :flaws, :dependent => :destroy
	 has_many :items, :dependent => :destroy
	 
	 validates :backstory, :presence => true, :length => { :minimum => 50 }
         validates :user_id, :presence => true
	 
	 default_scope :order => 'characters.character_name DESC'
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
        before_filter :authenticate, :only => [:index, :edit, :update]
        before_filter :correct_user, :only => [:edit, :update]
	
	layout "application", :except => [:race_div]
	
 def index
    @title = "My Characters"
    @characters =  Character.paginate(:page => params[:page])
  end	  



  def show
    @character = Character.find(params[:id])
    @title = @character.character_name
    @race_name = BaseStat.find(@character.race).race
    
    skills = @character.skills 
    @spent_exp = 0
    if (skills.nil?) then
       skills = []	    
    else 	    
      skills.each {|s|
        @spent_exp += s.skillcost
      } # end each s
    end # end else not nil.
    
    @skills_agility = []
    @skills_connection = []
    @skills_intellect = []
    @skills_magic = []
    @skills_might = []
    @skills_divine = []
    
    skills.each {|s|
      @skills_agility += [s] if s.category == 'agility'
      @skills_connection  += [s] if s.category == 'connection'
      @skills_intellect  += [s] if s.category == 'intellect'
      @skills_magic  += [s] if s.category == 'magic'
      @skills_might  += [s] if s.category == 'might'
      @skills_divine  += [s] if s.category == 'divine'
    }
    
    
    @gained_exp = 0
	    
    unless @character.experiences.nil? then
      @character.experiences.each {|xp|
        @gained_exp += xp.exp_gained
      } # end each exp
    end # end unless experiences = nil
    unless @character.flaws.nil? then
      @character.flaws.each {|xp|
        @gained_exp += xp.exp_value
      } # end each exp
    end # end unless flaw list = nil
    
end # end show function



  def new
    #@test = params.inspect
		
    # if a race has been chosen, use this to populate the starting stat fields,		
    # otherwise, use argead as default.
    if (params[:raceindex].nil? == false) then
        @race_base = BaseStat.find(params[:raceindex])
	@race_index = params[:raceindex]
    else
        @race_base = BaseStat.find(1)
	@race_index = 1
    end	    
	
    @character = Character.new
    @title = "New Character"
    @base_stats = BaseStat.all
    
    @boons = 0
    current_user.boons.each {|b|
      @boons += b.howmany
    }
    
    @sphere_list = []
    Spellinfo.all(:select => "distinct sphere").each { |s|
      @sphere_list += [s.sphere]
    }
  end


  # used by ajax to return the base values for the race submitted.
  # returns numbers only. numbers used to update specific elements in html page.
  def race_info 
	 @par = params.inspect
	
	if params[:raceindex].nil? then
	    @race_index = "argead"
	else
           @race_index = params[:raceindex]
        end
	
	#@base_stats = BaseStat.all
	@race_base =  BaseStat.find(@race_index) 
    	  
        #render :xml => @race_base
	render :json => @race_base
  end	  



   def create
    
	   
    @character = current_user.characters.build(params[:character])
    if @character.save
      flash[:success] = "New Character Created!"
      redirect_to @character
    else
      @title = "New Character"
      render 'new'
    end
    
    
  end #end create
  
  
  
  
  def destroy
    Character.find(params[:id]).destroy
    flash[:success] = "Character destroyed."
    redirect_to character_path
  end

  
  
   def edit
    @character = Character.find(params[:id])
    @title = "Edit Character"
    
    # @current_user = current_user	
    @skill_list = @character.skills
    # @skill_list = Attribute.all(:conditions => ["user_id = ?", @character.user.user_id], :order => " DESC")
      
    
  
  end



 def update
    @character = Character.find(params[:id])
    if @character.update_attributes(params[:character])
      flash[:success] = "Character updated."
      redirect_to @character
    else
      @title = "Edit character"
      render 'edit'
    end
end #end update
	
	
	
private	
	
    def authenticate
      deny_access unless signed_in?
    end

    def correct_user
      @character = Character.find(params[:id])
      @user = @character.user
      @user_id = @character.user_id

      redirect_to(root_path) unless current_user?(@user)
    end
	
end # end controller	
	

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_character.html.erb
<tr>
  <td class="character">
    <span class="content"><%= character.character_name %> - 
    <%= BaseStat.find(character.race).race %></span>
  </td>
<% user = character.user rescue User.find(character.user_id) %>
<% if current_user?(user) %>
  <td>
   <%= link_to "edit",  edit_character_path(character),
    :title => character.character_name %>
&nbsp; &nbsp;
  <%= link_to "view", character, 
    :action => :show,
    :title => character.character_name %>
&nbsp; &nbsp;    
        <%= link_to "delete", character, :method => :delete,
                                     :confirm => "You sure?",
                                     :title => character.character_name %>
  </td>
  <% end %>
</tr>

app/views/characters/edit.html.erb
<h1>Edit character</h1>

<%= form_for(@character) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <h1> <%= @character.character_name %> </h1>
  <div class="field">
    <%= f.label :character_name %><br />
    <%= f.text_field :character_name %>
  </div>
  
  <p></p>
  <fieldset>
    <legend>Agility (x<%= @character.multiplier_agility %>) </legend>
    <table>
      <tr>
        <td>
	  <%= @ambidexterity %>
	  Ambidexterity 
	  <button type='button'>+</button>
	  <button type='button'>-</button>
	</td>
	<td>
	  <%= @adac %>
	  ADAC
	  <button type='button'>+</button>
	  <button type='button'>-</button>
	</td>
	<td>
	  <%= @balance %>
	  Balance
	  <button type='button'>+</button>
	  <button type='button'>-</button>
	</td>
      </tr>
      
    </table>
  </fieldset>
  
  
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/characters/index.html.erb
<h1>Master Character List</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @characters %>
</ul>

<%= will_paginate %>

app/views/characters/new.html.erb
<script type="text/javascript">

var base_stat;

function message(text) {
  alert(text);
}

function change_multiplier() {
   // alert("called.\n");
      
    var diff = 0
    var neg_diff = 0
    var pos_diff = 0
    
    diff = $('character_multiplier_agility').value - base_stat['multiplier_agility'];
    if (diff > 0) {pos_diff += diff; } else {neg_diff += diff; }
    
    diff = $('character_multiplier_connection').value - base_stat['multiplier_connection'];
    if (diff > 0) {pos_diff += diff; } else {neg_diff += diff; }
    
    diff = $('character_multiplier_intellect').value - base_stat['multiplier_intellect'];
    if (diff > 0) {pos_diff += diff; } else {neg_diff += diff; }
    
    diff = $('character_multiplier_magic').value - base_stat['multiplier_magic'];
    if (diff > 0) {pos_diff += diff; } else {neg_diff += diff; }
    
    diff = $('character_multiplier_might').value - base_stat['multiplier_might'];
    if (diff > 0) {pos_diff += diff; } else {neg_diff += diff; }
    
    $('total_reductions').value = neg_diff
    $('total_increases').value = pos_diff
    
    //alert("finished.")
}


// this function obtains new base stats for the race chosen and updates 
// each multiplier element etc as appropriate. no need to reload an 
// entire div element.
function racial_change() {
  //alert("Boo1!");
  var race_choice = $('character_race');
  //alert("Boo2!");
  
  
  new Ajax.Request('race_info', {
    method: 'get',
    contentType: 'application/json',
    parameters: {raceindex: race_choice.value},
    onSuccess: function(transport) {
      //alert("Success!\n"+transport.responseJSON); 
      eval(transport.responseJSON)
      //alert("bing");
      var race_base = transport.responseJSON;
      //var race_text = transport.responseText;
      //alert("Obj:\n"+race_base["base_stat"]+"\nText:\n"+race_text);
      
      base_stat = race_base['base_stat']
      
      //alert("Values:\n"+base_stat['faith']);
      
      $('boondiv').update(base_stat['boon_cost']);
      $('character_deity').value = base_stat['deity'];
      $('character_faith').value = base_stat['faith'];
      $('character_starting_skillpts').value = base_stat['starting_skillpts']
      
      $('character_multiplier_agility').value = base_stat['multiplier_agility'];
      $('character_multiplier_connection').value = base_stat['multiplier_connection'];
      $('character_multiplier_intellect').value = base_stat['multiplier_intellect'];
      $('character_multiplier_magic').value = base_stat['multiplier_magic'];
      $('character_multiplier_might').value = base_stat['multiplier_might'];
      $('total_reductions').value = 0;
      $('total_increases').value = 0;
      
      $('character_loc').value = base_stat['loc'];
      $('character_halo').value = base_stat['halo'];
      $('character_willpower').value = base_stat['willpower'];
      $('character_mana').value = base_stat['mana'];
      $('character_con').value = base_stat['con'];
      $('character_primary_sphere').value = base_stat['primary_sphere'];
      
      var racial_mod = base_stat['racial_multiplier_mods'];
      $('racial_multiplier_div').update(racial_mod);
      
      $('racial_benefit_div').update(base_stat['racial_skills'])
      $('racial_ability_div').update(base_stat['racial_abilities'])
      $('racial_flaw_div').update(base_stat['racial_flaws'])
      
    },
    onFailure: function(transport){
      alert("There was an error accessing your racial template.\n"+
      "Please notify your web administrator. \n-Aegora");
    }  
  });
  
  
}

</script>


<h1>Create new character</h1>

<%= form_for(@character) do |f| %>
<%= render 'shared/error_messages', :object => f.object %>
<table class = 'profile' summary='New character generation form'>
<tr>
  <td class='main'>
  <table>
  <tr>
  <td>
  <div class="field">
    <%= f.label :character_name, "Character Name" %><br />
    <%= f.text_field :character_name %>
  </div>
  </td>
  <td>
  <div class="field">
    <%= f.label :race %><br />
    <%= f.select "race",
      options_from_collection_for_select(
          @base_stats, 
          :id, 
          :race,
	  @race_index
      ), {}, {:onchange => 'racial_change()'}
         
      %>
    </select>  
    <!-- <input type='button' onclick='racial_change()' value='ReFresh'/>  -->
   </div>
  </td>
  </tr>
  <tr>
  <td>
  <div class="field">
    <%= f.label :alignment %><br />
    <%= f.select :alignment, 
             options_for_select([
	     "lawful good hopeful",
	     "neutral good hopeful",
	     "chaotic good hopeful",
	     "lawful neutral hopeful",
	     "neutral neutral hopeful",
	     "chaotic neutral hopeful",
	     "lawful evil hopeful",
	     "neutral evil hopeful",
	     "chaotic evil hopeful",
		"lawful good neutral",
	     "neutral good neutral",
	     "chaotic good neutral",
	     "lawful neutral neutral",
	     "neutral neutral neutral",
	     "chaotic neutral neutral",
	     "lawful evil neutral",
	     "neutral evil neutral",
	     "chaotic evil neutral"
	     ], 
	        :selected => "lawful good hopeful")
	%>	
  </div>
  </td>
  <td>
  <div class="field">
    <%= f.label :gender %><br />
    <%= f.select :gender,
             options_for_select(["male", "female", "other"], 
	        :selected => "female")
	%>	
  </div>
  </td>
  </tr>
  </table>
  <table>
  <tr>
  <td>
 <div id='race_div'>
 
 Racial Boon Cost: <span id='boondiv'> <%= @race_base.boon_cost %></span><br />
*This number of boons will be deducted from your total should you choose this race. <br />
<br />

<div class='field'>
Starting skill points: <%= f.number_field :starting_skillpts, 
  :value => "#{@race_base.starting_skillpts}", :size => 5, :readonly => 'true' %>
</div>

<table>
<tr><td>
  <div class="field">
    <%= f.label :deity %>
    <%= f.text_field :deity, :value=>"#{@race_base.deity}" %>    
  </div>
</td><td>
  <div class='field'>
     <%= f.label :faith %>
     <%= f.number_field :faith, :size => 3, :readonly => 'true' %>
  </div>
</td></tr>  
</table>   

<fieldset>
  <legend>Starting Physical Statistics</legend>
  <table>
    <tr>
      <td>  
	<div class='field'>
	  <%= f.label :loc, "Location" %> <br />
	  <%= f.number_field :loc, :readonly=>'true', :value=>"#{@race_base.loc}", :size=>5 %>
        </div>
      </td>
      <td>  
	<div class='field'>
	  <%= f.label :con, "Constitution" %> <br />
	  <%= f.number_field :con, :readonly=>'true', :value=>"#{@race_base.con}", :size=>5%>
        </div>
      </td>
       <td>  
	<div class='field'>
	  <%= f.label :halo, "Halo" %> <br />
	  <%= f.number_field :halo, :readonly=>'true', :value=>"#{@race_base.halo}", :size=>5%>
        </div>
      </td>
    </tr>
    <tr>    
     <td>  
	<div class='field'>
	  <%= f.label :con, "Willpower" %> <br />
	  <%= f.number_field :willpower, :readonly=>'true', :value=>"#{@race_base.willpower}", :size=>5 %>
        </div>
      </td>
       <td>  
	<div class='field'>
	  <%= f.label :mana, "Mana" %> <br />
	  <%= f.number_field :mana, :readonly=>'true', :value=>"#{@race_base.mana}", :size=>5%>
        </div>
      </td>
      <td>
        <div class='field'>
	  <%= f.label :primary_sphere, "Primary Sphere" %> <br />
	  <%= f.select :primary_sphere,  options_for_select(@sphere_list, 
	    :selected => "#{@race_base.primary_sphere}") 
	  %>  
	</div>
      </td>
    </tr>
  </table>
</fieldset>

<fieldset>
<legend>Skill Multipliers</legend>


<!-- If your racial type has a bonus to the skill multipliers (as do elves) then, display this info. -->
<div id='racial_multiplier_div'>
<% if @race_base.racial_multiplier_mods.nil? == false then %>
<p><strong>Racial Modifiers:</strong><%= @race_base.racial_multiplier_mods %></p>
<% end %>
</div>

<table>
  <tr>
  <td valign="top">
  <div class="field">
    <%= f.label :multiplier_agility, "Agility" %><br />
    <%= f.select :multiplier_agility, 
             options_for_select([ 1, 2, 3, 4, 5, 6, 7, 8, 9 ], @race_base.multiplier_agility),{},
	     :onchange => "change_multiplier()"
	     %>	<br />	
  </div> </td>
  
   <td valign="top"><div class="field">
    <%= f.label :multiplier_connection, "Connection" %> <br />
    <%=  f.select :multiplier_connection, 
             options_for_select([ 1, 2, 3, 4, 5, 6, 7, 8, 9 ],  @race_base.multiplier_connection),{},
	     :onchange=>"change_multiplier()"
	     %>	<br />		
  </div></td>
  
   <td valign="top"><div class="field">
     <%= f.label :multiplier_intellect, "Intellect" %> <br />
     <%= f.select :multiplier_intellect, 
             options_for_select([ 1, 2, 3, 4, 5, 6, 7, 8, 9 ], @race_base.multiplier_intellect), {},
	     :onchange=>"change_multiplier()"
	     %>		<br />	
  </div></td>
   <td valign="top"><div class="field">
     <%= f.label :multiplier_magic, "Magic" %> <br />
     <%= f.select :multiplier_magic, 
             options_for_select([ 1, 2, 3, 4, 5, 6, 7, 8, 9 ], @race_base.multiplier_magic),{},
	     :onchange=>"change_multiplier()"
	     %>		<br />	
  </div></td>
   <td valign="top"><div class="field">
     <%= f.label :multiplier_might, "Might" %> <br />
     <%= f.select :multiplier_might, 
             options_for_select([ 1, 2, 3, 4, 5, 6, 7, 8, 9 ], @race_base.multiplier_might),{},
	     :onchange=>"change_multiplier()"
	     %>	<br />	
  </div></td>
  </tr>
  </table>
  <table><tr>
  <td>
  Total Reductions: 
  <input type='number' id='total_reductions' readonly='true' value=0 size=5>
  </td>
  <td>
  Total Increases: 
  <input type='number' id='total_increases' readonly='true' value=0 size=5>
  </td>
  </tr></table>
  </fieldset>
  
  <fieldset>
    <legend>Racial Benefits </legend>
      <div id='racial_benefit_div'>
         
      </div>
  </fieldset>
  
    <fieldset>
    <legend>Racial Abilities </legend>
      <div id='racial_ability_div'>
         
      </div>
  </fieldset>
  
    <fieldset>
    <legend>Racial Flaws </legend>
      <div id='racial_flaw_div'>
         
      </div>
  </fieldset>
  
 </div>
  </td>
  </tr>
  <tr>
    <td>  
       <div class="field">
         <%= f.label :backstory %>*<br />
         <%= f.text_area :backstory %><br />
         *Must be longer than 50 characters.
       </div>
    </td>
 </tr>
</table>

  </td>
  <td class="sidebar round">
      Available Boons: 
      <span id='boon_display_area'> <%= @boons %>  </span>
      <br /> <br />
   
      <p><small>
Multiplier Reductions are set to the base values for the race you choose from the dropdown list. 
You may decrease your multipliers
by three (to a minimum of 1) as you desire. You may also increase two of your multipliers 
by one to obtain an additional reduction point, however, this can be done only once.
If your race is eligible for additional multiplier reductions, this will be noted above your multiplier 
selection box.
</small></p>
   
   
   <br />

  </td>
</tr>
</table>
  
  
  <div class="actions">
    <%= f.submit "Create" %>
  </div>
 
<% end %>

app/views/characters/race_info.html.erb
<%= @race_base.to_json %>

app/views/characters/show.html.erb
<table class="profile" summary="Character information">
  <tr>
    <td class="main">
      <h1>
        <%= @character.character_name %>
      </h1>
        <table>
	  <tr>
	    <td><strong>Race:</strong> <%= @race_name %> </td>
	    <td><strong>Alignment:</strong> <%= @character.alignment %> </td>
	  </tr>
	  </table>
	  <table>
	  <tr>
	  <td><strong>Level:</strong> <%= @spent_exp / 25 %></td>
	  <td><strong>Spent XP: </strong><%= @spent_exp %></td>
	  <td><strong>Total XP:</strong> <%= @gained_exp %></td>
	  </tr>
	  <tr>
	    <td><strong>Loc:</strong> <%= @character.loc %></td>
	    <td><strong>Con:</strong> <%= @character.con %></td>
	    <td><strong>Halo: </strong><%= @character.halo %></td>
	    <td><strong>Will: </strong><%= @character.willpower %></td>
	    <td><strong>Mana: </strong><%= @character.mana %></td>
	  </tr>
	</table>
	<% if @skills_agility.size > 0 then %>
        <table class="skills" summary="agility skills">
          <tr> 
	    <th>Agility (x
	      <%= @character.multiplier_agility %>)</th>
	  </tr>
          <tr> <td>
	     <% @skills_agility.each_with_index {|s, i|  %>
	       <strong><%= s.rank %></strong>&nbsp; &nbsp;
	       <%= s.skill_name %> <%= s.skill_subtype.nil? ? '' : '('+s.skill_subtype+')' %>
	       <% if i % 4 == 0 then %>
	         </td><td>
	       <% end %>	 
	     <% } %>
          </td></tr>	  
        </table>
        <% end %>
	<% if @skills_connection.size > 0 then %>
        <table class="skills" summary="connection skills">
          <tr> 
	    <th>Connection (x
	      <%= @character.multiplier_connection %>)</th>
	  </tr>
          <tr> <td>
	     <% @skills_connection.each_with_index {|s, i|  %>
	       <strong><%= s.rank %></strong>&nbsp; &nbsp;
	       <%= s.skill_name %> <%= s.skill_subtype.nil? ? '' : '('+s.skill_subtype+')' %>
	       <% if i % 4 == 0 then %>
	         </td><td>
	       <% end %>	 
	     <% } %>
          </td></tr>	  
        </table>
	<% end %>
	<% if @skills_intellect.size > 0 then %>
        <table class="skills" summary="intellect skills">
          <tr> 
	    <th>Intellect (x
	      <%= @character.multiplier_intellect %>)</th>
	  </tr>
          <tr> <td>
	     <% @skills_intellect.each_with_index {|s, i|  %>
	       <strong><%= s.rank %></strong>&nbsp; &nbsp;
	       <%= s.skill_name %> <%= s.skill_subtype.nil? ? '' : '('+s.skill_subtype+')' %>
	       <% if i % 4 == 0 then %>
	         </td><td>
	       <% end %>	 
	     <% } %>
          </td></tr>	  
        </table>
	<% end %>
	<% if @skills_magic.size > 0 then %>
        <table class="skills" summary="magic skills">
          <tr> 
	    <th>Magic (x
	      <%= @character.multiplier_magic %>)</th>
	  </tr>
          <tr> <td>
	     <% @skills_magic.each_with_index {|s, i|  %>
	       <strong><%= s.rank %></strong>&nbsp; &nbsp;
	       <%= s.skill_name %> <%= s.skill_subtype.nil? ? '' : '('+s.skill_subtype+')' %>
	       <% if i % 4 == 0 then %>
	         </td><td>
	       <% end %>	 
	     <% } %>
          </td></tr>	  
        </table>
	<% end %>
	<% if @skills_might.size > 0 then %>
        <table class="skills" summary="might skills">
          <tr> 
	    <th>Might (x
	      <%= @character.multiplier_might %>)</th>
	  </tr>
          <tr> <td>
	     <% @skills_might.each_with_index {|s, i|  %>
	       <strong><%= s.rank %></strong>&nbsp; &nbsp;
	       <%= s.skill_name %> <%= s.skill_subtype.nil? ? '' : '('+s.skill_subtype+')' %>
	       <% if i % 4 == 0 then %>
	         </td><td>
	       <% end %>	 
	     <% } %>
          </td></tr>	  
        </table>
	<% end %>
	<% if @skills_divine.size > 0 then %>
        <table class="skills" summary="divine skills">
          <tr> 
	    <th>Divine (x
	      <%= @character.multiplier_magic %>)</th>
	  </tr>
          <tr> <td>
	     <% @skills_divine.each_with_index {|s, i|  %>
	       <strong><%= s.rank %></strong>&nbsp; &nbsp;
	       <%= s.skill_name %> <%= s.skill_subtype.nil? ? '' : '('+s.skill_subtype+')' %>
	       <% if i % 4 == 0 then %>
	         </td><td>
	       <% end %>	 
	     <% } %>
          </td></tr>	  
        </table>
	<% end %>
	
	
	
	<% if @character.flaws.size > 0 then %>
	<strong>Flaws:</strong><br />
	<p>
	<% @character.flaws.each {|f| %>
	  <%= f.flaw_type %>
	  <% if f.exp_value > 0 then %>
	    (<%= f.exp_value %>)
	  <% end %>  	
	  <br />
	<% } %>
	</p>
	<% end %>
	
	
	<% if @character.items.size > 0 then %>
	<strong>Inventory:</strong><br />
	<table>
	<% @character.items.each {|it| %>
	 <tr>
	   <td> 
	     <%= it.howmany > 0 ? '' : it.howmany %>
	     <%= it.what %> 
	   </td>
	   <td align='center'><%= it.value.nil? ? ' ' :  it.value.to_s+' sp' %> </td>
	   <td align='right' colspan = 6> <%= it.expiry_date %> </td>
	 </tr><tr>
	   <td colspan = 6 rowspan = 3><%= it.description %></td>
	 </tr>
	<% } %>
	</table>
	
	<% end %>
	
    </td>
  </tr>
</table>